### PR TITLE
#93 and #94

### PR DESCRIPTION
**Pull request by MXMX0811**
Use platform package check the OS and generate the dynamic lib according to the OS. Add the install require of numpy.

### CODE REVIEW

**Comment by s5suzuki** [comment]
Could you also update ".github/workflows/release.yml" for uploading platform-specific packages to PyPI?

**Comment by MXMX0811** [comment]
Sorry, I don't understand where should be modified in the release.yml... I am not very familiar with the usage of PyPI. I think the platform-specific operation is all conducted in the setup.py?

**Comment by s5suzuki** [comment]
GitHub actions is used to upload whl package to PyPI when a new version is released so that pyautd3 can be installed with pip.
Currently, this "publish_pypi" step is only executed on "ubuntu-latest", which means that only linux whl is uploaded to PyPI.

**Comment by s5suzuki** [comment]
If you are not familiar with GitHub actions or PyPI, I will be happy to handle the remaining tasks for you.

**Comment by s5suzuki** [comment]
Also, could you please do the following tasks?
- [ ] Remove pyautd3/bin/**/* if it exist to avoid error when setup.py is executed multiple times
- [ ] Generate platform-specific whl file. Currently, the whl name is `pyautd3-<VERSION>-py3-none-any.whl` for all platforms. [This link](https://stackoverflow.com/questions/73962721/how-to-create-platform-specific-python-wheel-with-build-tool) might be helpful.

**Comment by s5suzuki** [comment]
Of course, these tasks are not urgent, so I would appreciate it if you could work on them when you have time.

**Comment by MXMX0811** [comment]
OK, thank you very much!

**Comment by MXMX0811** [comment]
I tried to modify the release.yml, but I am not sure if it is correct... Please have a look at it.

**Comment by s5suzuki** [comment]
Unfortunately, I don't think it will work correctly as it is.
First, you are uploading whl with a job such as `publish_mac`, but this is an upload to PyPI, not to a GitHub artifact, so this data cannot be downloaded in `publish_pypi` job. 
The only thing that needs to be changed is the `publish_pypi` job, which should be changed to run on all OS. (You can use `strategy.matrix` for this. See, for example, `build.yml`).
Also, now all whl filenames are `pyautd3-13.0.0-py3-none-any.whl` on all OS. Thus, only the earliest executed OS package will be uploaded.

**Comment by MXMX0811** [comment]
I have modified the release.yml again.

**Comment by s5suzuki** [comment]
I got an error `error: invalid command 'win_amd64'` on my local windows machine.

**Comment by MXMX0811** [comment]
By the way, how can I test the release.yml? I'm afraid that some test operations will upload some strange version and cause difficulties to the version management.

**Comment by s5suzuki** [comment]
There is [Self-hosted runnner](https://docs.github.com/en/actions/hosting-your-own-runners) or tools like [act](https://github.com/nektos/act). However, Self-hosted runner is not recommended to use for public repo, and act can only run Linux actions.

**Comment by s5suzuki** [comment]
The easiest way is to try it anyway, and if you make a mistake, re-upload with a newer patch version.

**Comment by MXMX0811** [comment]
I have modified the setup.py and successfully generated plat-specific .whl. But I don't know if there will be other problems on linux and macos.

**Comment by MXMX0811** [comment]
But I still don't know why use plat-name parameter like `python setup.py sdist bdist_wheel --plat-name=win_amd64` cannot give the correct wheel... It will also give a whl with `none` platform.

**Comment by s5suzuki** [comment]
I have read [Setuptools documentation](https://setuptools.pypa.io/en/latest/userguide/quickstart.html#setup-py), and I notice that the method using `setup.py` is not recommended. How about changing to the method using `setup.cfg`?

**Comment by MXMX0811** [comment]
I have found the problem. The `plat-name` parameter can be changed when only `bdist_wheel` is used. But when use `python setup.py sdist bdist_wheel`, the parameter cannot take effect. Is there any way to seperate them as 2 steps?

**Comment by s5suzuki** [comment]
I noticed that a platform-specific package will be generated if it contains C extensions. Therefore, I decided to include empty C extensions (although I am not sure if this is the right way to handle this...)
Also, I change almost setup.py to setup.cfg. See https://github.com/shinolab/autd3/commit/a162591d4bc1182fb48c5815d8aae1556a1e98f0 for example.

**Comment by MXMX0811** [comment]
The example of only changing the yaml that I referred to is [.github/workflows/main.yml at 0c6cf99](https://github.com/bytecodealliance/wasmtime-py/actions/runs/2941452867/workflow). 

Actually I also noticed the use of setup.cfg like [link](https://stackoverflow.com/questions/72090919/how-to-configure-setuptools-with-setup-cfg-to-include-platform-name-python-tag). But it seems that there still some problems on abi tags?

**Comment by s5suzuki** [comment]
What is problems on abi tags?

**Comment by MXMX0811** [comment]
The abi tag is still `none` in the [link](https://stackoverflow.com/questions/72090919/how-to-configure-setuptools-with-setup-cfg-to-include-platform-name-python-tag) when using setup.cfg (I don't if we also have the same problem).

**Comment by s5suzuki** [comment]
Yes. whl packages with c extention have some problem. abi tag cannot be specified and python version is fixed. I think the best way is to specify the plat-name with `--build-option`.
See https://github.com/shinolab/autd3/commit/60db213b51ff95c19dd7aefd3cc4ea52f46ed799.

**Comment by s5suzuki** [comment]
To check if it works, I created a `release-py-patch.yml` action just to upload the patch version and published v14.0.1.1 to PyPI in https://github.com/shinolab/autd3/commit/42fe4201dee7217472d2e9d7bb0e3779c5dc8405.
Does it work correctly? I will close this issue when it will be confirmed that it works correctly on all platforms (windows-x64, macos-x64 and arm64, linux-x64).

**Comment by MXMX0811** [comment]
I got an error `ModuleNotFoundError: No module named 'requests'` when test it on my local mac although I have already installed the package `requests`.

**Comment by MXMX0811** [comment]
And this `ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel`

**Comment by s5suzuki** [comment]
That's quite strange... pyautd3 does not depend on `requests`.

**Comment by MXMX0811** [comment]
Yes, I also think so... Later I will also try it on windows. I'm sorry I didn't provide any actual help on this problem...

**Comment by MXMX0811** [comment]
Ah, I have overlooked `download_bin.py`. It can be runned correctly!

**Comment by s5suzuki** [comment]
Having verified that the OS-specific packages are installed and working properly on Windows/macOS/Linux, I close this Issue.

**Pull request closed without merging**
