### PR TITLE
#127 reopen

### PR DESCRIPTION
**Pull request by MXMX0811**
Please check if the Fourier is correctly defined in the primitive.hpp.

### CODE REVIEW

**Comment by s5suzuki** [comment]
`Sine` seems to be fine, but `Fourier` in cpp is not. Current implementation can only handle one sine component.

**Comment by MXMX0811** [comment]
I want to implement the function like: `m.add_component(m1).add_component(m2)`... If the current program can not do that, could you please give me some tips? I also would like to ask how to transform the `autd3::modulation::Sine` to `internal::native_methods::ModulationPtr` in cpp.

**Comment by s5suzuki** [comment]
I didn't check if it will work fine, but it should be like this:
```cpp
class Fourier final : public internal::Modulation {
 public:
  Fourier() = default;

  Fourier add_component(Sine component) {
    _components.emplace_back(component);
    return std::move(*this);
  }

  [[nodiscard]] internal::native_methods::ModulationPtr modulation_ptr() const override {
    return std::accumulate(_components.begin(), _components.end(), internal::native_methods::AUTDModulationFourier(), [](internal::native_methods::ModulationPtr ptr, Sine sine) {
        return internal::native_methods::AUTDModulationFourierAddComponent(ptr, sine.modulation_ptr());
    });
  }

 private:
  std::vector<Sine> _components;
};
```

**Comment by MXMX0811** [comment]
Ah, I see. My previous idea was to continuously add waveforms onto the first waveform rather than storing all waveforms into a vector. Thank you very much!

**Comment by s5suzuki** [comment]
In Rust, all variables are moved when they are used, except for the basic copyable type. Therefore, a value cannot be reused once it has been used.
For example, the following (pseudo) code is illegal in Rust, and cannot be compiled. (Actually, `Sine` implements `Copy` trait, so the code below is legal.)
```rust
let a = Sine::new();
autd.send(a);
autd.send(a);
```
However, probably, no one expects code like the above to be illegal in C++/C#/Python. The Rust compiler prevents the above code from being compiled, but the C++/C# compiler does not. Also, Python interpreter does not prevent the above code from being executed. If you simply write code that wraps the library, for example, generating Rust resources in the constructor and using them around, the above code will cause serious errors.
(In C++, there is a way to force programmers to use move semantics, but it is tedious to write `std::move` every time, so I decided not to do so.)

To address this problem, each wrapper library has a policy of keeping the data to generate rust resources in each language side and generating resources in rust only when they are actually needed.
Thus, the implementation of `Fourier` must be something like the above.

**Pull request closed without merging**
