### PR TITLE
Added cpp api of sine with phase

### PR DESCRIPTION
**Pull request by MXMX0811**

### CODE REVIEW

**Comment by MXMX0811** [comment]
If the usage of the extern is correct?

```rust
#[no_mangle]
#[must_use]
pub unsafe extern "C" fn AUTDModulationFourier(m1: ModulationPtr, m2: ModulationPtr) -> ModulationPtr {
    ModulationPtr::new(take_mod!(m1, Fourier).add_component(m2))
}

#[no_mangle]
#[must_use]
pub unsafe extern "C" fn AUTDModulationFourierIter(m: ModulationPtr, m_vec: Vec<f64>) -> ModulationPtr {
    ModulationPtr::new(take_mod!(m, Fourier).add_components_from_iter(m_vec))
}
```

**Comment by s5suzuki** [comment]
No. `m2` must be cast as `Sine`, and `Vec<T>` is a Rust's type and cannot be used in C ABI.

**Comment by s5suzuki** [comment]
It would be better to prepare only the code to add a single component and handle the iterator in each language.
For examples, see https://github.com/shinolab/autd3/blob/0cabab8592e7c59e17fa9eb415f694cd8050dd98/dotnet/cs/src/AUTD3Sharp.cs#L1087C1-L1090C14, https://github.com/shinolab/autd3/blob/0cabab8592e7c59e17fa9eb415f694cd8050dd98/python/pyautd3/stm/stm.py#L129C1-L139C1, and https://github.com/shinolab/autd3/blob/0cabab8592e7c59e17fa9eb415f694cd8050dd98/cpp/include/autd3/internal/stm.hpp#L149C1-L156C4

**Comment by MXMX0811** [comment]
I noticed that the component member of Fourier is `components: Vec<Sine>`, and when I use `cargo build` there's an error: 

```
error[E0308]: mismatched types
   --> autd3capi\src\lib.rs:565:66
    |
565 |     ModulationPtr::new(take_mod!(fourier, Fourier).add_component(*take_mod!(m, Sine)))
    |                                                    ------------- ^^^^^^^^^^^^^^^^^^^ expected `Sine`, found `Box<Sine>`
    |                                                    |
    |                                                    arguments to this method are incorrect
    |
    = note: expected struct `autd3capi_def::autd3capi_common::Sine`
               found struct `Box<autd3capi_def::autd3capi_common::Sine>`
note: method defined here
   --> C:\Users\zmxle\Desktop\HapisLab\autd3\src\autd3\src\modulation\fourier.rs:40:12
    |
40  |     pub fn add_component(self, sine: Sine) -> Self {
    |            ^^^^^^^^^^^^^
help: consider unboxing the value
    |
565 |     ModulationPtr::new(take_mod!(fourier, Fourier).add_component(**take_mod!(m, Sine)))
    |
```

So should it be `**take_mod!(m, Sine)` but not `*take_mod!(m, Sine)`?

**Comment by s5suzuki** [comment]
Sorry, I renamed `master` branch to `main`, then this PR was automatically closed...

**Comment by s5suzuki** [comment]
Also, I have set up a check process before merging to verify codes can be built. 
So, please change the base branch to "develop" and open the pull requests again.

**Pull request closed without merging**
